name: Node.js CI/CD
run-name: ${{ inputs.name }}

on:
  workflow_dispatch:
    inputs:
      name:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm i
    - run: npm run build

    - name: Rename main1 to main
      run: |
        if [ -f main1.js ]; then
          mv main1.js main.js
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sheets-basic
        path: |
          main.js
          manifest.json
          styles.css
